### ISSUE TITLE
Get Infoboxes by Page

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/defexpand#4]
I am trying to make sense of how defexpand can be used to scrape a Wikipedia [xml dump](https://dumps.wikimedia.org/enwiki/20150304/) (presumably `enwiki-20150304-pages-articles.xml.bz2`) to get each page's infobox(es). I want to use this functionality to populate the [WikiThingsDB](https://github.com/infolab-csail/wikithingsdb). So far, as I understand, `scripts/WikiExtractor.py` contains an [`extract_infoboxes()` function](https://github.com/infolab-csail/defexpand/blob/infoboxes/scripts/WikiExtractor.py#L658-L667) that is used to [`update_infobox_summary()`](https://github.com/infolab-csail/defexpand/blob/infoboxes/scripts/WikiExtractor.py#L670-L677) that is output in a JSON file to the [`summary_dir`](https://github.com/infolab-csail/defexpand/blob/infoboxes/scripts/WikiExtractor.py#L635-L640). However, there are a whole bunch of other [options and arguments](https://github.com/infolab-csail/defexpand/blob/infoboxes/scripts/WikiExtractor.py#L42-L56) to the `WikiExtractor.py` script, which I don't know much about. I don't need the script to output a [million different files](http://medialab.di.unipi.it/wiki/Wikipedia_Extractor) of [parsed Wikipedia pages](https://github.com/infolab-csail/defexpand/blob/infoboxes/scripts/WikiExtractor.py#L42-L56); all I need is the page --> infobox(es) data. How do I do this?

The goals here are:
1.  Figure out and document exactly _how_ to call the `WikiExtractor.py` script so that it outputs the desired infoboxes by page data. Update the README with instructions.
2.  Fix any problems along the way if this functionality is incomplete, has bugs, etc.

I have created a `infoboxes` branch for this issue.

@alvaromorales or @moldot, do you have any hints as to how `WikiExtractor.py` is used?

**Comment by alvaromorales** [comment]
Run:

`$ bzip2 -dc /path/to/pages-articles.xml.bz2 | python /path/to/WikiExtractor.py -l -o extracted`

Where `pages-articles.xml.bz2` is the latest pages bz2 dump file (e.g. http://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2)

This will write many files in the directory `extracted`. Make sure that this directory is under `/scratch`. Go to `navassa:/scratch/varot/defexpand/extracted for sample output`.

Each article is converted into a <doc> tag, example:

```
<doc id="340" url="http://en.wikipedia.org/wiki?curid=340" title="Alain Connes" infobox="scientist">
Alain Connes

Alain Connes (; born 1 April 1947) is a French mathematician, currently Professor at the Collège de France, IHÉS, The Ohio State University and Vanderbilt University.
## Work.
Alain Connes studies operator algebras. In his early work on von Neumann algebras in the 1970s, he succeeded in obtaining the almost complete classification of injective factors. Following this he made contributions in operator K-theory and index theory, which culminated in the
Baum-Connes conjecture. He also introduced cyclic cohomology in the early 1980s as a first step in the study of noncommutative differential geometry.
Connes has applied his work in areas of mathematics and theoretical physics, including number theory, differential geometry and particle physics.
## Awards and honours.
Connes was awarded the Fields Medal in 1982, the Crafoord Prize in 2001 and the gold medal of the CNRS in 2004. He is a member of the French Academy of Sciences and several foreign academies and societies, including the Danish Academy of Sciences, Norwegian Academy of Sciences, Russian Academy of Sciences, and US National Academy of Sciences.

</doc>
```

From `<doc id="340" url="http://en.wikipedia.org/wiki?curid=340" title="Alain Connes" infobox="scientist">` you'll be able to extract the wiki id (pages foreign key), title, and one or more infoboxes.

The JSON summary is for informational purposes, and for calculating the `infobox_counts.tsv` file. For your purpose (getting infoboxes for each article), you should just look at the `extracted` directory. This script should be good as-is.

You'll notice that elasticstart also has a scripts/WikiExtractor.py file. A task (_for later_) is to consolidate the scripts and move it to a repository that makes sense. This is a cleanup task that I will address later.

**Comment by michaelsilver** [comment]
Awesome, thanks for the clear explanation! I'm currently downloading/parsing.

I've also updated the README and usage; created PR #5. Feel free to add or otherwise merge if good.

Also, for future reference, is it possible to curl/bzip/python it in one step like this:

```
$ curl http://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2 | bzip2 -dc /path/to/pages-articles.xml.bz2 | python /path/to/WikiExtractor.py -l -o extracted
```

(I'm currently parsing an old dump and downloading a new one, so no CPU room on machine to try now, but maybe next time).
